[project]
name = "pymonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "opencv-python-headless>=4.13.0.92",
    "playsound3>=3.3.1",
    "psutil>=7.2.2",
    "pydantic-settings>=2.13.1",
    "python-telegram-bot>=22.6",
    "wmi>=1.5.1; sys_platform == 'win32'",
]

[dependency-groups]
dev = [
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-kroki-plugin>=1.6.0",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
    "properdocs>=1.6.7",
    "pyinstaller>=6.19.0",
    "ruff>=0.16.5",
]
